### ISSUE TITLE
Problem when try to call an another Rest-api at Botframework-V3+C#.net

### ISSUE THREAD

**Issue by tutul2010** [microsoft/BotFramework-Services#172]
Hi,
I stuck with a problem as..
When i was trying to call another Rest Api end point (Rest-api done at dotnetcore 2.1) by Post-verb method at Botframework-V3+C#.net .
Problem is like as debugger point(at Visual studio 2017 IDE) was not returning to Botframework-V3 code after calling to api.
The Rest-Api app (developed at dotnetcore 2.1) was done by our team and it is working file by Postman tool and also cors enable for access.
At Below ,Exception msgs are coming at Botframework-V3,C#.net code base
```

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at QnABot.Services.ApiServicesCall.<VmCreationApiServPostApi>d__3.MoveNext()
```
I am not using async-wait at Rest-api. Rest-api is working fine by Postman .rest-api code as below

```
[Route("api/[controller]")]
    [ApiController]
    public class VmCreationController : ControllerBase
    {
	 [HttpPost]
        [Consumes(MediaTypeNames.Application.Json)]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [EnableCors]
        [Route("VmCreationServices")]
        //http://localhost:50817/api/VmCreation/VmCreationServices
        public  ActionResult<Boolean> VmCreationServices([FromBody] ServiceVmCreation ObjVmModel)
              {   
			//code for call a powershell script
			return true;
		}
	}
```
Below is code at Botframework-V3+C#.net on how am i calling above rest-api

```
[Serializable]
public class ApiServicesCall 
    {
        HttpClient client = new HttpClient();
        string UrlApi = "";
        public  ApiServicesCall()
        {
            UrlApi = ConfigurationSettings.AppSettings["SERVICE_URL"].ToString(); // get as http://localhost:50817/api/
            client.BaseAddress = new Uri(UrlApi);
        }
		public  async Task<bool> VmCreationServPostApi(VmConfigVwModel apiPayload ,string vmService_PostUrl)
        {
            bool fFlg=false;
            dynamic jsonObject = "";
            if (apiPayload == null)
                return fFlg;
            // rest-api  calling by Post
            try
            {
                var json = JsonConvert.SerializeObject(apiPayload);
                var stringContent = new StringContent(json, System.Text.Encoding.UTF8, "application/json");
                string urlParameters = vmService_PostUrl; //as "VmCreation/VmCreationServices";

                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage responseTask = await client.PostAsync(urlParameters, stringContent);
                //responseTask.Wait();
                //var result = responseTask.Result;
                if (responseTask.IsSuccessStatusCode) //200->ok
                {
                    var apiResponse =  responseTask.Content.ReadAsStringAsync();
                    fFlg = true;    
                }
            }
            catch (Exception e)
            {
                fFlg = true;
            }
          return fFlg;
        }	
	}
```
Please help.

Thanks,
Tutul

**Comment by mdrichardson** [comment]
Closing, as this [is a duplicate](https://github.com/microsoft/BotBuilder-V3/issues/177)

**Comment by tutul2010** [comment]
Pls #closed as it is a time Out issue by HttpClient.
