### ISSUE TITLE
Getting error while connecting to qna maker

### ISSUE THREAD

**Issue by mukeshhope** [microsoft/BotFramework-Services#177]
Hi Team,
I am new to BotFramework services.
I am trying to connect to qna maker but i am getting error. i am trying to test QnAmaker from send message and its working fine. But when i am testing from local bot framework emulator , i am getting below error message (i have extracted error by sending the error message in response).

```
Cannot read property ‘endsWith’ of undefinedTypeError: Cannot read property ‘endsWith’ of undefined 
at HttpRequestUtils.getHeaders (D:\home\site\wwwroot\node_modules\botbuilder-ai\lib\qnamaker-utils\httpRequestUtils.js:69:48) 
at HttpRequestUtils.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder-ai\lib\qnamaker-utils\httpRequestUtils.js:47:34) at Generator.next (<anonymous>) 
at D:\home\site\wwwroot\node_modules\botbuilder-ai\lib\qnamaker-utils\httpRequestUtils.js:14:71 at new Promise (<anonymous>) 
at __awaiter (D:\home\site\wwwroot\node_modules\botbuilder-ai\lib\qnamaker-utils\httpRequestUtils.js:10:12) 
at HttpRequestUtils.executeHttpRequest (D:\home\site\wwwroot\node_modules\botbuilder-ai\lib\qnamaker-utils\httpRequestUtils.js:37:16) 
at GenerateAnswerUtils.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder-ai\lib\qnamaker-utils\generateAnswerUtils.js:64:63) 
at Generator.next (<anonymous>) 
at D:\home\site\wwwroot\node_modules\botbuilder-ai\lib\qnamaker-utils\generateAnswerUtils.js:14:71
```

please help me.
Please let me know if i should provide some more information.

**Comment by dmvtech** [comment]
Hi @mukeshhope Can you give me a bit more information around what you mean by:

> test QnAmaker from send message and its working fine

Is this a bot from scratch or are you running a certain sample?  or did you create a bot from yeoman/visx? if you used a sample; is it one of the qna samples?

If you can share a (sanitized of personal, sensitive info) reproduction of this in another repository, then that might help me determine what is going on.

**Comment by mukeshhope** [comment]
Hi Dana,
Thank you so much for your response.
I tried to get a response of qna maker from postman and it works fine (this is what i mean by sending a message to qna maker and works fine.)
i made a call to 
https://muct-bot-service.azurewebsites.net/qnamaker/knowledgebases/<myknowledgenaseid>/generateAnswer
from post man and i am getting correct response.
![Captureqnaresponse](https://user-images.githubusercontent.com/18657453/73722524-b94ae000-474c-11ea-85d4-e6ffb78e6977.PNG)

I was trying to follow tutorial from Microsoft  and created an empty chat bot in typescript.
and yes i created from yoman. 
if you say i will share the files but i have not written much . i have just followed the guidelines on below url to connect bot to qnamaker.
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp

below is the code i have in onMessage event

` this.onMessage(async (context, next) => {
            
            let qnaResults:any={};
            let error:string = "";
            try{
             qnaResults = await this.qnaMaker.getAnswers(context);
            }catch(e)
                {
                    error = (e as Error).message + (e as Error).stack
                    
                }
            await context.sendActivity(error);
            // If an answer was received from QnA Maker, send the answer back to the user.
            if (qnaResults[0]) {
                await context.sendActivity(`QnAMaker returned response: ' ${ qnaResults[0].answer}`);
            }
            else {
                // If no answers were returned from QnA Maker, reply with help.
                await context.sendActivity('No QnA Maker response was returned.'
                    + 'This example uses a QnA Maker Knowledge Base that focuses on smart light bulbs. '
                    + `Ask the bot questions like "Why won't it turn on?" or "I need help."`);
            }
            await next();
        });`
you can see i have send the error to see what error is coming. error is coming when i am trying to get answer from qna maker.
Please let me know if i can provide some more information to troubleshoot.

**Comment by dmvtech** [comment]
Can you try the following sample:

https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/11.qnamaker

I want to make sure that runs correctly first. If so, then we can figure out what the difference might be between the two.

**Comment by mukeshhope** [comment]
Hi Dana,

Sure i will try and let you know

**Comment by mukeshhope** [comment]
Hi Dana,
I tried running sample suggested by you and it works !. 

Also i found that my env file has double quotes in properties and i removed that.

I removed node_modules folder and run npm install.
again and now i am getting below error.
text: "Cannot read property 'map' of undefinedTypeError: Cannot read property 'map' of undefined at GenerateAnswerUtils.formatQnaResult (C:\Mukesh\Mukesh\rnd\myjsbot\my-test-bot\node_modules\botbuilder-ai\lib\qnamaker-utils\generateAnswerUtils.js:125:47) at GenerateAnswerUtils.<anonymous> (C:\Mukesh\Mukesh\rnd\myjsbot\my-test-bot\node_modules\botbuilder-ai\lib\qnamaker-utils\generateAnswerUtils.js:64:25) at Generator.next (<anonymous>) at fulfilled (C:\Mukesh\Mukesh\rnd\myjsbot\my-test-bot\node_modules\botbuilder-ai\lib\qnamaker-utils\generateAnswerUtils.js:12:58) at processTicksAndRejections (internal/process/task_queues.js:93:5) "

with same .env configuration sample bot is working but my type script bot is not working.

Please have a look on my index.ts file
`// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import { config } from 'dotenv';
import * as path from 'path';
import * as restify from 'restify';

// Import required bot services.
// See https://aka.ms/bot-services to learn more about the different parts of a bot.
import { BotFrameworkAdapter } from 'botbuilder';

// This bot's main dialog.
import { EchoBot } from './bot';

const ENV_FILE = path.join(__dirname, '..', '.env');
config({ path: ENV_FILE });
const configuration = {
    knowledgeBaseId: process.env.QnAKnowledgebaseId,
    endpointKey: process.env.QnAAuthKey,
    host: process.env.QnAEndpointHostName
 };
// Create HTTP server.
const server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, () => {
    console.log(`\n${server.name} listening to ${server.url}`);
    console.log('\nGet Bot Framework Emulator: https://aka.ms/botframework-emulator');
    console.log('\nTo talk to your bot, open the emulator select "Open Bot"');
});

// Create adapter.
// See https://aka.ms/about-bot-adapter to learn more about adapters.
const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});

// Catch-all for errors.
const onTurnErrorHandler = async (context, error) => {
    // This check writes out errors to console log .vs. app insights.
    // NOTE: In production environment, you should consider logging this to Azure
    //       application insights.
    console.error(`\n [onTurnError] unhandled error: ${ error }`);

    // Send a trace activity, which will be displayed in Bot Framework Emulator
    await context.sendTraceActivity(
        'OnTurnError Trace',
        `${ error }`,
        'https://www.botframework.com/schemas/error',
        'TurnError'
    );

    // Send a message to the user
    await context.sendActivity('The bot encountered an error or bug.');
    await context.sendActivity('To continue to run this bot, please fix the bot source code.');
};

// Set the onTurnError for the singleton BotFrameworkAdapter.
adapter.onTurnError = onTurnErrorHandler;

// Create the main dialog.
const myBot = new EchoBot(configuration,{});

// Listen for incoming requests.
server.post('/api/messages', (req, res) => {
    adapter.processActivity(req, res, async (context) => {
        // Route to main dialog.
        await myBot.run(context);
    });
});

// Listen for Upgrade requests for Streaming.
server.on('upgrade', (req, socket, head) => {
    // Create an adapter scoped to this WebSocket connection to allow storing session data.
    const streamingAdapter = new BotFrameworkAdapter({
        appId: process.env.MicrosoftAppId,
        appPassword: process.env.MicrosoftAppPassword
    });
    // Set onTurnError for the BotFrameworkAdapter created for each connection.
    streamingAdapter.onTurnError = onTurnErrorHandler;

    streamingAdapter.useWebSocket(req, socket, head, async (context) => {
        // After connecting via WebSocket, run this logic for every request sent over
        // the WebSocket connection.
        await myBot.run(context);
    });
});
`

bot.ts file
`// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import { ActivityHandler, MessageFactory } from 'botbuilder';
const { QnAMaker } = require('botbuilder-ai');
export class EchoBot extends ActivityHandler {
    qnaMaker:any={};
    constructor(configuration,qnaOptions) {
        super();
         if (!configuration) throw new Error('[QnaMakerBot]: Missing parameter. configuration is required');
         // now create a qnaMaker connector.
        
         this.qnaMaker = new QnAMaker(configuration, qnaOptions);
        // See https://aka.ms/about-bot-activity-message to learn more about the message and other activity types.
        this.onMessage(async (context, next) => {
            
            let qnaResults:any;
            let error:string="test";
            try{
             qnaResults = await this.qnaMaker.getAnswers(context);
            }catch(e)
                {
                    error=(e as Error).message + (e as Error).stack;
                    
                    error = error + " : test";
                    
                }
                await context.sendActivity(configuration.host);
                await context.sendActivity(configuration.knowledgeBaseId);
                await context.sendActivity(configuration.endpointKey);
                await context.sendActivity(error);
                if (qnaResults[0]) {
                    await context.sendActivity(qnaResults[0].answer);
    
                // If no answers were returned from QnA Maker, reply with help.
                } else {
                    await context.sendActivity('No QnA Maker answers were found.');
                }
            await next();
        });

        this.onMembersAdded(async (context, next) => {
            const membersAdded = context.activity.membersAdded;
            const welcomeText = 'Hello and welcome!';
            for (const member of membersAdded) {
                if (member.id !== context.activity.recipient.id) {
                    await context.sendActivity(MessageFactory.text(welcomeText, welcomeText));
                }
            }
            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });
    }
}
`

I was following step by step guide and trying to connect  to qna maker. 
Please let me know if i can help you with some more information

**Comment by dmvtech** [comment]
Looks like you have a mismatch between your code and .env. In your code you are using **QnAAuthKey** and in the .env it is **QnAEndpointKey**.

```
const configuration = {
    knowledgeBaseId: process.env.QnAKnowledgebaseId,
    endpointKey: process.env.QnAAuthKey,
    host: process.env.QnAEndpointHostName
 };
```
```
QnAKnowledgebaseId=
QnAEndpointKey=
QnAEndpointHostName=
```

one small change should get it working:
```
const configuration = {
    knowledgeBaseId: process.env.QnAKnowledgebaseId,
    endpointKey: process.env.QnAEndpointKey,
    host: process.env.QnAEndpointHostName
 };
 ```

**Comment by mukeshhope** [comment]
Hi Dana,
Yes it worked.
Thank you so much. you are superman.
