### ISSUE TITLE
Telegram channel returns POST to chatbot failed: POST to the bot's endpoint failed with HTTP status 500

### ISSUE THREAD

**Issue by fenris** [microsoft/BotFramework-Services#197]
Intermittent having this issue with my chatbot using qnamaker channeling through Telegram bot

Log Stream output:

> [onTurnError] unhandled error: Error: Bad Request: BUTTON_DATA_INVALID(node:6108) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERRORReferenceError: InputHints is not definedat BotFrameworkAdapter.adapter.onTurnError [as turnError] (D:\home\site\wwwroot\index.js:46:72)at process._tickCallback (internal/process/next_tick.js:68:7)at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:687:27)at Generator.throw (<anonymous>)at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:65)at process._tickCallback (internal/process/next_tick.js:68:7)(node:6108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 69)
> Running dialog with Message Activity.
> [onTurnError] unhandled error: Error: Bad Request: BUTTON_DATA_INVALID(node:6108) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERRORReferenceError: InputHints is not definedat BotFrameworkAdapter.adapter.onTurnError [as turnError] (D:\home\site\wwwroot\index.js:46:72)at process._tickCallback (internal/process/next_tick.js:68:7)at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:687:27)at Generator.throw (<anonymous>)at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:65)at process._tickCallback (internal/process/next_tick.js:68:7)(node:6108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 72)
> 2020-03-26T18:51:17  No new trace in the past 1 min(s).
> 2020-03-26T18:52:17  No new trace in the past 2 min(s).
> 2020-03-26T18:53:17  No new trace in the past 3 min(s).
> 2020-03-26T18:54:17  No new trace in the past 4 min(s).
> Running dialog with Message Activity.
> Running dialog with Message Activity.
> [onTurnError] unhandled error: Error: Bad Request: BUTTON_DATA_INVALID
> (node:6108) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERRORReferenceError: InputHints is not definedat BotFrameworkAdapter.adapter.onTurnError [as turnError] (D:\home\site\wwwroot\index.js:46:72)at process._tickCallback (internal/process/next_tick.js:68:7)at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:687:27)at Generator.throw (<anonymous>)at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:65)at process._tickCallback (internal/process/next_tick.js:68:7)(node:6108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 75)

**Comment by v-kydela** [comment]
Hello @fenris 

It looks like your bot code is throwing an error that has something to do with button data. Button payloads are formatted differently in different channels so it's likely that your bot isn't programmed to adapt its payloads to Telegram.

In order to help you, we will need to see your relevant bot code and we will need repro steps that explain what user/bot interactions take place when this problem occurs.

If you would like to debug your bot code yourself while using the Telegram channel, you can use a tunneling service like ngrok: https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

**Comment by v-kydela** [comment]
@fenris - Are you still working on this?

**Comment by fenris** [comment]
Hi,
Sorry for the late reply.

Please find the link of the bot source code for your perusal.

https://1drv.ms/u/s!AopkDJYAZ52wp9d3t7cj31nBcjCiow?e=zNxzvV

**Comment by v-kydela** [comment]
@fenris - Thank you for the bot code. I have removed the link so that your secret keys remain secure. Would you please provide steps that would allow me to reproduce the error while running your bot?

**Comment by fenris** [comment]
Thanks Kyle,
Sorry forgot to remove the secret keys from that source file.

I just deployed the bot once i've published the qnamaker. Then I channeled
it to the telegram bot.
After that start session with the telegram bot and start asking questions

**Comment by v-kydela** [comment]
@fenris - Are you saying you encounter the error no matter what message you send to the bot? It's not related to the cards and buttons that are part of multi-turn QnA prompts? You encounter the error when you say "hello"?

**Comment by fenris** [comment]
It's intermittent .. sometimes the errors is not occurs ..

Please find the attached screenshot

**Comment by fenris** [comment]
is it because there is too many or lengthy messages replied/ fast respond by the bot to telegram?

**Comment by v-kydela** [comment]
@fenris - It looks like your Markdown isn't getting rendered in your email replies. Please reply directly in GitHub

![screenshot-chat-with-bot](https://user-images.githubusercontent.com/405473/78184167-a1b57c80-749b-11ea-9694-472c5f591afb.jpg)

**Comment by v-kydela** [comment]
From the screenshot, the error does not look intermittent. It looks like you can reproduce it consistently using specific questions. Is that the case? Can you tell me what the bot's response to that question was supposed to be?

**Comment by fenris** [comment]
here are the expected reply as screenshot

![qnamaker-test](https://user-images.githubusercontent.com/405473/78203965-f1f80300-74ca-11ea-9bee-6540d9cf17d7.jpg)

**Comment by v-kydela** [comment]
@fenris - So you're not expecting any buttons? That's very strange that the error message you posted is about button data.

**Comment by fenris** [comment]
the words "kilang-kilang" occurs below errors:

> [onTurnError] unhandled error: Error: Bad Request: BUTTON_DATA_INVALID
(node:14520) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERRORReferenceError: InputHints is not definedat BotFrameworkAdapter.adapter.onTurnError [as turnError] (D:\home\site\wwwroot\index.js:46:72)at process._tickCallback (internal/process/next_tick.js:68:7)
at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:687:27)at Generator.throw (<anonymous>)at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:65)at process._tickCallback (internal/process/next_tick.js:68:7)(node:14520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)(node:14520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Running dialog with Message Activity.
[onTurnError] unhandled error: Error: Bad Request: BUTTON_DATA_INVALID(node:14520) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERROR
ReferenceError: InputHints is not definedat BotFrameworkAdapter.adapter.onTurnError [as turnError] (D:\home\site\wwwroot\index.js:46:72)at process._tickCallback (internal/process/next_tick.js:68:7)at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:687:27)at Generator.throw (<anonymous>)at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:65)at process._tickCallback (internal/process/next_tick.js:68:7)(node:14520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

Got this as recent chat with the telegram bot : "POST to pkp-bot timed out after 15s"
Yeah, its really strange ...

**Comment by v-kydela** [comment]
@fenris - Are you saying you're seeing the error in the log stream blade of your app service resource in the Azure portal?

**Comment by v-kydela** [comment]
When I try the phrase "kilang-kilang" it does send me a card with buttons:

![image](https://user-images.githubusercontent.com/41968495/78280528-19040400-74ce-11ea-8fe0-51912d49dfe5.png)

It seems your bot is programmed to disambiguate possible QnA pairs. Does that response not look familiar to you?

**Comment by fenris** [comment]
inside qnamaker test, it doesn't show card  but inside my emulator & Test in web chat (azure portal) shown exactly like your yours with the card. 

Is it a limitation from telegram to post multiples cards?

**Comment by v-kydela** [comment]
@fenris - No, it's not a limitation to post multiple cards to Telegram. Are you saying you're able to post one card to Telegram and you're only encountering the error when you try to send subsequent cards?

**Comment by fenris** [comment]
yeah .... you are right ..

**Comment by v-kydela** [comment]
@fenris - Can you show me what the card looks like in Telegram?

**Comment by v-kydela** [comment]
@fenris - Are you still working on this?

**Comment by v-kydela** [comment]
Closing due to inactivity
