### ISSUE TITLE
Unable to Send attachment using directline but there is not an issue if we are using emulator.

### ISSUE THREAD

**Issue by dstvishnu** [microsoft/BotFramework-Services#253]
Unable to send an attachment using directline but we are not facing an issue if we use it from an emulator. We are using a directline channel for communicating between mobile app and bot.
We are receiving the below error in the bot logs and this occurs in a loop two or three times.

```
2020-09-23T08:30:57.729043066Z [41m[30mfail[39m[22m[49m: Middleware[0]
2020-09-23T08:30:57.729074167Z       Unhandled exception in request pipeline: System.Net.Http.HttpRequestException: An error occurred while sending the request.
2020-09-23T08:30:57.729079167Z        ---> System.IO.IOException: The response ended prematurely.
2020-09-23T08:30:57.729166167Z          at System.Net.Http.HttpConnection.FillAsync()
2020-09-23T08:30:57.729174167Z          at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
2020-09-23T08:30:57.729250367Z          at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
2020-09-23T08:30:57.729265767Z          --- End of inner exception stack trace ---
2020-09-23T08:30:57.729269367Z          at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
2020-09-23T08:30:57.729340068Z          at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2020-09-23T08:30:57.729416968Z          at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2020-09-23T08:30:57.729424568Z          at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2020-09-23T08:30:57.729550569Z          at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2020-09-23T08:30:57.729559869Z          at Microsoft.Azure.AppService.MiddlewareShim.Startup.ForwardRequestAsync(HttpContext context) in /EasyAuth/Middleware.Host/Startup.cs:line 204
2020-09-23T08:30:57.729635369Z          at Microsoft.Azure.AppService.MiddlewareShim.Startup.OnRequest(HttpContext context) in /EasyAuth/Middleware.Host/Startup.cs:line 151
```

the version of botbuilder used is 4.9.1

**Comment by v-kydela** [comment]
Thank you for the report, @dstvishnu. I would like to help but I have a few questions.

1. Are you sending the attachment from the bot to a Direct Line client or are you sending the attachment from a Direct Line client to the bot?
1. What is the attachment?
1. Can you share any relevant code and repro steps?

**Comment by dstvishnu** [comment]
Hi @v-kydela 

1.We are sending an attachment from bot to directline.
2.Attachment is a simple .jpeg image of size around 200 kb.
3. In the bot side in one step we will prompt the user to provide a screenshot.

```
async getScreenshotStep(stepContext: WaterfallStepContext) {
      const promptOptions = {
        prompt: 
          "Please attach a screenshot"
      };
      return await stepContext.prompt(
        ATTACHMENT_PROMPT,
        promptOptions
      );
    }
    return await stepContext.next();
  }
```
  
  ```
async storeScreenshotStep(stepContext:WaterfallStepContext){
	if (
      stepContext.context.activity.attachments &&
      stepContext.context.activity.attachments.length > 0
    ) {
      let files: string[] = new Array();
      for (let attachment of stepContext.context.activity.attachments) {
        let attachementInfo: AttachmentInfo = await this.downloadAttachmentAndWrite(
          attachment,
          stepContext.context.activity.conversation.id
        );
        if (attachementInfo.fileName) {
          files.push(attachementInfo.fileName);
        }
        attachmentFileInfos.push(attachementInfo);
      }
	  await stepContext.context.sendActivity(
        "Received attachments."
        );
	}
	return await stepContext.next();	
  }
```

**Comment by v-kydela** [comment]
@dstvishnu - I'm sorry but I'm a bit confused by your answers. In your answer to question 1 you say you're sending the attachment from the bot to Direct Line, meaning the attachment is in a bot-to-user message. But in your answer to question 3 you say you're prompting the user to provide a screenshot, implying that the attachment is in a user-to-bot message. Which is it?

**Comment by dstvishnu** [comment]
@v-kydela sorry for the confusion. We are sending image mobile to bot. I updated the comment

**Comment by v-kydela** [comment]
@dstvishnu - Thank you for the clarification. In that case I have some more questions for you.

4. Does the bot receive the activity at all or does the request fail before it reaches the bot? To answer this, you may want to run your bot locally and have Direct Line send messages to it through a tunneling service like ngrok.
5. Are you able to send an image attachment to your bot using the [Direct Line API](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts) directly instead of using your mobile app? You can try that with any HTTP client like cURL or Postman.

**Comment by dstvishnu** [comment]
@v-kydela  
4. We received the activity in the bot but from directline, we are getting the activity again and again.
5. We are able to send the image using the Bot Framework Emulator without any issue

**Comment by v-kydela** [comment]
@dstvishnu - For your answer to question 4, I will need some more information to clarify what you're saying.

6. Are you saying the bot is processing the activity correctly or is just receiving the activity and not processing it correctly? You had said at the start that you're unable to send an attachment but now it's sounding like you are able to send it and you're just encountering errors along the way.
7. Is the problem just that the client is reporting the errors or would you consider the bot getting duplicate activities an additional problem on top of that?
8. Is there a specific number of times your bot receives the activity? This sounds like it could have to do with Direct Line retrying the message because it doesn't get a response from the bot.
9. Is your mobile app sending the activity multiple times or does your mobile app just send it to Direct Line once?

You still haven't answered question 5. Emulator is irrelevant here because it doesn't use Direct Line. I need you to try the Direct Line API.

**Comment by v-kydela** [comment]
@dstvishnu - Are you still working on this?

**Comment by dstvishnu** [comment]
@v-kydela We can close this issue.There was a bug in our code. We resolved it. Thanks for the help.
